### PR TITLE
Update exercise 2

### PR DESCRIPTION
**Pull request by charlesmcchan**
- [x] Update EXERCISE-2.md
- [x] Mount mininet folder into mininet container
- [x] Update a few diagrams
- [x] Add solution netcfg
- [x] Fix REUSE license check
- [x] Update Step 5 Dump packets to see VLAN tags
- [x] Fix dynamic interface update issue - flows for h3 and h4 not populated after interface config is corrected
- [x] Fix repeating warning from UP4 (Won't do. Will try to disable pfcp-agent)
  ```
  05:34:59.990 WARN [Up4NorthComponent] UP4 client attempted to read or write to logical switch before an app config was loaded. 
  05:34:59.990 INFO [Up4NorthComponent] Received ARBITRATION on StreamChannel 
  05:34:59.996 INFO [Up4NorthComponent] Blindly telling requester with election_id high: 1652247299 low: 989706132 they are the primary controller
  ```

### CODE REVIEW

**Comment by charlesmcchan** [comment]
- @ccascone How do we want to handle the UP4 error? Should we push the UP4 app config or disable the UP4 app?
- The dynamic interface config issue may require more time. I am wondering if @pierventre can help? Current workaround is to remove the host and discover it again.

**Comment by pierventre** [comment]
what's the issue ?

**Comment by charlesmcchan** [comment]
@pierventre follow the instruction in `EXERCISE-2.md` all the way to the end:
- Push a netcfg without leaf2 interfaces
- Discover h3 when trying to ping (but ping will fail)
- Fix and push the netcfg by adding leaf2 interfaces
- h3 still can't ping, since the routing table entry is not re-populated when the interface config is updated (BUG)
- Removing h3 and let it discover again (with correct interface config) can fix the issue

**Comment by ccascone** [comment]
@charlesmcchan I'm aware of the warning and I'm trying different approaches, you can ignore this for now. I would like to push the up4 config as part of the p4-upf exercise. I'm trying to find a way to not start pfcp-agent until the p4-upf exercise.

**Comment by pierventre** [comment]
@charlesmcchan https://gerrit.onosproject.org/c/trellis-control/+/25475. I would like to do other tests...I dont have a lot of infrastructure for testing but I would like to run a couple of runs more.

**Comment by pierventre** [comment]
is it ready for review ?

**Comment by charlesmcchan** [comment]
> is it ready for review ?

Yes

**Comment by charlesmcchan** [comment]
Considering the size of this patch and the approaching deadline, @ccascone and I decided to merge this first and we will do an overall review once all the parts are done.

**Pull request merged**
